// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;
using AUTD3Sharp.Utils;
using AUTD3Sharp.Link;


namespace AUTD3Sharp.NativeMethods
{
    internal static unsafe partial class NativeMethodsAutd3Core
    {
        const string __DllName = "autd3_core";

        internal const byte TRANSITION_MODE_SYNC_IDX = 0;
        internal const byte TRANSITION_MODE_SYS_TIME = 1;
        internal const byte TRANSITION_MODE_GPIO = 2;
        internal const byte TRANSITION_MODE_EXT = 240;
        internal const byte TRANSITION_MODE_NONE = 254;
        internal const byte TRANSITION_MODE_IMMEDIATE = 255;
        internal const float ABSOLUTE_THRESHOLD_OF_HEARING = 0.00002f;
        internal const nuint ULTRASOUND_PERIOD_COUNT_BITS = 9;
        internal const nuint EC_OUTPUT_FRAME_SIZE = 626;
        internal const nuint EC_INPUT_FRAME_SIZE = 2;
        internal const double EPSILON = 0.000001;



    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct Angle
    {
        public float radian;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct Drive
    {
        public Phase phase;
        public EmitIntensity intensity;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct EmitIntensity
    {
        public byte Item1;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct Phase
    {
        public byte Item1;
    }


    internal enum GPIOOut : byte
    {
        O0 = 0,
        O1 = 1,
        O2 = 2,
        O3 = 3,
    }

    internal enum GPIOIn : byte
    {
        I0 = 0,
        I1 = 1,
        I2 = 2,
        I3 = 3,
    }

    internal enum Segment : byte
    {
        S0 = 0,
        S1 = 1,
    }


}
