// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;
using AUTD3Sharp.Utils;
using AUTD3Sharp.Link;


namespace AUTD3Sharp.NativeMethods
{
    

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct BesselOption
    {
        public EmitIntensity intensity;
        public Phase phase_offset;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct FocusOption
    {
        public EmitIntensity intensity;
        public Phase phase_offset;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct PlaneOption
    {
        public EmitIntensity intensity;
        public Phase phase_offset;
    }


    internal enum ParallelMode : byte
    {
        Auto = 0,
        On = 1,
        Off = 2,
    }


}
