// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;
using AUTD3Sharp.Utils;
using AUTD3Sharp.Link;


namespace AUTD3Sharp.NativeMethods
{
    internal static unsafe partial class NativeMethodsGainHolo
    {
        const string __DllName = "autd3capi_gain_holo";



        [DllImport(__DllName, EntryPoint = "AUTDGainHoloConstraintNormalize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern EmissionConstraintWrap AUTDGainHoloConstraintNormalize();

        [DllImport(__DllName, EntryPoint = "AUTDGainHoloConstraintUniform", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern EmissionConstraintWrap AUTDGainHoloConstraintUniform(EmitIntensity intensity);

        [DllImport(__DllName, EntryPoint = "AUTDGainHoloConstraintMultiply", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern EmissionConstraintWrap AUTDGainHoloConstraintMultiply(float v);

        [DllImport(__DllName, EntryPoint = "AUTDGainHoloConstraintClamp", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern EmissionConstraintWrap AUTDGainHoloConstraintClamp(EmitIntensity min_v, EmitIntensity max_v);

        [DllImport(__DllName, EntryPoint = "AUTDGainHoloGreedySphere", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern GainPtr AUTDGainHoloGreedySphere(Point3* points, float* amps, uint size, GreedyOption option);

        [DllImport(__DllName, EntryPoint = "AUTDGainHoloGreedyT4010A1", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern GainPtr AUTDGainHoloGreedyT4010A1(Point3* points, float* amps, uint size, GreedyOption option);

        [DllImport(__DllName, EntryPoint = "AUTDGainGreedyIsDefault", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool AUTDGainGreedyIsDefault(GreedyOption option);

        [DllImport(__DllName, EntryPoint = "AUTDGainHoloGSSphere", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern GainPtr AUTDGainHoloGSSphere(BackendPtr backend, Point3* points, float* amps, uint size, GSOption option);

        [DllImport(__DllName, EntryPoint = "AUTDGainHoloGST4010A1", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern GainPtr AUTDGainHoloGST4010A1(BackendPtr backend, Point3* points, float* amps, uint size, GSOption option);

        [DllImport(__DllName, EntryPoint = "AUTDGainGSIsDefault", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool AUTDGainGSIsDefault(GSOption option);

        [DllImport(__DllName, EntryPoint = "AUTDGainHoloGSPATSphere", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern GainPtr AUTDGainHoloGSPATSphere(BackendPtr backend, Point3* points, float* amps, uint size, GSPATOption option);

        [DllImport(__DllName, EntryPoint = "AUTDGainHoloGSPATT4010A1", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern GainPtr AUTDGainHoloGSPATT4010A1(BackendPtr backend, Point3* points, float* amps, uint size, GSPATOption option);

        [DllImport(__DllName, EntryPoint = "AUTDGainGSPATIsDefault", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool AUTDGainGSPATIsDefault(GSPATOption option);

        [DllImport(__DllName, EntryPoint = "AUTDGainHoloSPLToPascal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern float AUTDGainHoloSPLToPascal(float value);

        [DllImport(__DllName, EntryPoint = "AUTDGainHoloPascalToSPL", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern float AUTDGainHoloPascalToSPL(float value);

        [DllImport(__DllName, EntryPoint = "AUTDGainHoloLMSphere", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern GainPtr AUTDGainHoloLMSphere(BackendPtr backend, Point3* points, float* amps, uint size, LMOption option);

        [DllImport(__DllName, EntryPoint = "AUTDGainHoloLMT4010A1", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern GainPtr AUTDGainHoloLMT4010A1(BackendPtr backend, Point3* points, float* amps, uint size, LMOption option);

        [DllImport(__DllName, EntryPoint = "AUTDGainLMIsDefault", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool AUTDGainLMIsDefault(LMOption option);

        [DllImport(__DllName, EntryPoint = "AUTDGainHoloNaiveSphere", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern GainPtr AUTDGainHoloNaiveSphere(BackendPtr backend, Point3* points, float* amps, uint size, NaiveOption option);

        [DllImport(__DllName, EntryPoint = "AUTDGainHoloNaiveT4010A1", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern GainPtr AUTDGainHoloNaiveT4010A1(BackendPtr backend, Point3* points, float* amps, uint size, NaiveOption option);

        [DllImport(__DllName, EntryPoint = "AUTDGainNaiveIsDefault", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool AUTDGainNaiveIsDefault(NaiveOption option);

        [DllImport(__DllName, EntryPoint = "AUTDNalgebraBackendSphere", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern BackendPtr AUTDNalgebraBackendSphere();

        [DllImport(__DllName, EntryPoint = "AUTDNalgebraBackendT4010A1", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern BackendPtr AUTDNalgebraBackendT4010A1();

        [DllImport(__DllName, EntryPoint = "AUTDDeleteNalgebraBackendSphere", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void AUTDDeleteNalgebraBackendSphere(BackendPtr backend);

        [DllImport(__DllName, EntryPoint = "AUTDDeleteNalgebraBackendT4010A1", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void AUTDDeleteNalgebraBackendT4010A1(BackendPtr backend);


    }

    [StructLayout(LayoutKind.Explicit)]
    internal unsafe partial struct EmissionConstraintValue
    {
        [FieldOffset(0)]
        public EmitIntensity @null;
        [FieldOffset(0)]
        public EmitIntensity uniform;
        [FieldOffset(0)]
        public float multiply;
        [FieldOffset(0)]
        public fixed byte/* EmitIntensity, this length is invalid so must keep pointer and can't edit from C# */ clamp[2];
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct EmissionConstraintWrap
    {
        public EmissionConstraintTag tag;
        public EmissionConstraintValue value;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct GreedyOption
    {
        public EmissionConstraintWrap constraint;
        public byte phase_div;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct GSOption
    {
        public EmissionConstraintWrap constraint;
        public uint repeat;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct GSPATOption
    {
        public EmissionConstraintWrap constraint;
        public uint repeat;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct BackendPtr
    {
        public IntPtr Item1;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct LMOption
    {
        public EmissionConstraintWrap constraint;
        public float eps_1;
        public float eps_2;
        public float tau;
        public uint k_max;
        public float* initial;
        public uint initial_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct NaiveOption
    {
        public EmissionConstraintWrap constraint;
    }


    internal enum EmissionConstraintTag : byte
    {
        Normalize = 1,
        Uniform = 2,
        Multiply = 3,
        Clamp = 4,
    }


}
