// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;
using AUTD3Sharp.Utils;
using AUTD3Sharp.Link;


namespace AUTD3Sharp.NativeMethods
{
    internal static unsafe partial class NativeMethodsLinkTwinCAT
    {
        const string __DllName = "autd3capi_link_twincat";



        [DllImport(__DllName, EntryPoint = "AUTDLinkTwinCATTracingInit", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void AUTDLinkTwinCATTracingInit();

        [DllImport(__DllName, EntryPoint = "AUTDLinkTwinCATTracingInitWithFile", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ResultStatus AUTDLinkTwinCATTracingInitWithFile(byte* path);

        [DllImport(__DllName, EntryPoint = "AUTDLinkTwinCAT", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ResultLink AUTDLinkTwinCAT();

        [DllImport(__DllName, EntryPoint = "AUTDLinkRemoteTwinCAT", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ResultLink AUTDLinkRemoteTwinCAT(byte* server_ams_net_id, byte* server_ip, byte* client_ams_net_id);


    }



}
