// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;
using AUTD3Sharp.Utils;
using AUTD3Sharp.Link;


namespace AUTD3Sharp.NativeMethods
{
    internal static unsafe partial class NativeMethodsModulationAudioFile
    {
        const string __DllName = "autd3capi_modulation_audio_file";



        [DllImport(__DllName, EntryPoint = "AUTDModulationAudioFileTracingInit", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void AUTDModulationAudioFileTracingInit();

        [DllImport(__DllName, EntryPoint = "AUTDModulationAudioFileTracingInitWithFile", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ResultStatus AUTDModulationAudioFileTracingInitWithFile(byte* path);

        [DllImport(__DllName, EntryPoint = "AUTDModulationAudioFileWav", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ResultModulation AUTDModulationAudioFileWav(byte* path);

        [DllImport(__DllName, EntryPoint = "AUTDModulationAudioFileCsv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ResultModulation AUTDModulationAudioFileCsv(byte* path, SamplingConfigWrap sampling_config, byte delimiter);


    }



}
