// <auto-generated/>

#if UNITY_2020_2_OR_NEWER
#nullable enable
#endif

using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace AUTD3Sharp.Modulation {
    public partial class Square
    {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
        [ExcludeFromCodeCoverage]
        public Square WithLow(global::AUTD3Sharp.EmitIntensity value)
        {
           Low = value;
           return this;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        [ExcludeFromCodeCoverage]
        public Square WithLow(byte value)
        {
           Low = new EmitIntensity(value);
           return this;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        [ExcludeFromCodeCoverage]
        public Square WithHigh(global::AUTD3Sharp.EmitIntensity value)
        {
           High = value;
           return this;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        [ExcludeFromCodeCoverage]
        public Square WithHigh(byte value)
        {
           High = new EmitIntensity(value);
           return this;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        [ExcludeFromCodeCoverage]
        public Square WithDuty(float value)
        {
            Duty = value;
            return this;
        }
    }   
}