// <auto-generated/>

#if UNITY_2020_2_OR_NEWER
#nullable enable
#endif

using System;
using System.Diagnostics.CodeAnalysis;

namespace AUTD3Sharp.Gain.Holo {
    public partial class GSPAT<TB>
    {
                public GSPAT<TB> WithRepeat(uint value)
        {
            Repeat = value;
            return this;
        }
    }   
}