// <auto-generated/>

#if UNITY_2020_2_OR_NEWER
#nullable enable
#endif

using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace AUTD3Sharp.Timer {
    public partial class SpinSleeper
    {
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        [ExcludeFromCodeCoverage]
        public SpinSleeper WithSpinStrategy(global::AUTD3Sharp.NativeMethods.SpinStrategyTag value)
        {
            SpinStrategy = value;
            return this;
        }
    }   
}

#if UNITY_2020_2_OR_NEWER
#nullable restore
#endif
