// <auto-generated/>

#if UNITY_2020_2_OR_NEWER
#nullable enable
#endif

using System;
using System.Diagnostics.CodeAnalysis;

namespace AUTD3Sharp.Gain {
    public partial class Bessel
    {
        


        public Bessel WithIntensity(global::AUTD3Sharp.EmitIntensity value)
        {
           Intensity = value;
           return this;
        }

        [ExcludeFromCodeCoverage] public Bessel WithIntensity(byte value)
        {
           Intensity = new EmitIntensity(value);
           return this;
        }
        public Bessel WithPhaseOffset(global::AUTD3Sharp.Phase value)
        {
            PhaseOffset = value;
            return this;
        }
    }   
}