// <auto-generated/>

#if UNITY_2020_2_OR_NEWER
#nullable enable
#endif

using System;
using System.Diagnostics.CodeAnalysis;

namespace AUTD3Sharp.Modulation {
    public partial class Square
    {
        
        public Square WithLow(global::AUTD3Sharp.EmitIntensity value)
        {
           Low = value;
           return this;
        }

        [ExcludeFromCodeCoverage] public Square WithLow(byte value)
        {
           Low = new EmitIntensity(value);
           return this;
        }
        public Square WithHigh(global::AUTD3Sharp.EmitIntensity value)
        {
           High = value;
           return this;
        }

        [ExcludeFromCodeCoverage] public Square WithHigh(byte value)
        {
           High = new EmitIntensity(value);
           return this;
        }
        public Square WithDuty(double value)
        {
            Duty = value;
            return this;
        }
        public Square WithMode(global::AUTD3Sharp.SamplingMode value)
        {
            Mode = value;
            return this;
        }
    }   
}