// <auto-generated/>

#if UNITY_2018_3_OR_NEWER
#define USE_SINGLE
#endif

#if UNITY_2020_2_OR_NEWER
#nullable enable
#endif

#if USE_SINGLE
using float_t = System.Single;
#else
using float_t = System.Double;
#endif

using System;
using System.Diagnostics.CodeAnalysis;

namespace AUTD3Sharp.Gain {
    public partial class Uniform
    {
        
        public Uniform WithPhase(global::AUTD3Sharp.Phase value)
        {
            Phase = value;
            return this;
        }
    }   
}