// <auto-generated/>

#if UNITY_2020_2_OR_NEWER
#nullable enable
#endif

using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace AUTD3Sharp {
    public partial class SilencerFixedCompletionSteps
    {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
        [ExcludeFromCodeCoverage]
        public SilencerFixedCompletionSteps WithStrictMode(bool value)
        {
            StrictMode = value;
            return this;
        }
    }   
}