// <auto-generated/>

#if UNITY_2020_2_OR_NEWER
#nullable enable
#endif

using System;
using System.Diagnostics.CodeAnalysis;

namespace AUTD3Sharp.Gain.Holo {
    public partial class SDP<TB>
    {
                public SDP<TB> WithAlpha(double value)
        {
            Alpha = value;
            return this;
        }
        public SDP<TB> WithLambda(double value)
        {
            Lambda = value;
            return this;
        }
        public SDP<TB> WithRepeat(uint value)
        {
            Repeat = value;
            return this;
        }
    }   
}