// <auto-generated/>

#if UNITY_2020_2_OR_NEWER
#nullable enable
#endif

using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace AUTD3Sharp {
    public partial class SilencerFixedUpdateRate
    {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
        [ExcludeFromCodeCoverage]
        public SilencerFixedUpdateRate WithTarget(global::AUTD3Sharp.SilencerTarget value)
        {
            Target = value;
            return this;
        }
    }   
}