// <auto-generated/>

#if UNITY_2020_2_OR_NEWER
#nullable enable
#endif

using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace AUTD3Sharp {
    public partial class AUTD3
    {
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        [ExcludeFromCodeCoverage]
        public AUTD3 WithRotation(global::AUTD3Sharp.Utils.Quaternion value)
        {
            Rotation = value;
            return this;
        }
    }   
}