// <auto-generated/>

#if UNITY_2020_2_OR_NEWER
#nullable enable
#endif

using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace AUTD3Sharp.Link {
    public partial class RemoteTwinCATBuilder
    {
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        [ExcludeFromCodeCoverage]
        public RemoteTwinCATBuilder WithServerIp(string value)
        {
            ServerIp = value;
            return this;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        [ExcludeFromCodeCoverage]
        public RemoteTwinCATBuilder WithClientAmsNetId(string value)
        {
            ClientAmsNetId = value;
            return this;
        }
    }   
}

#if UNITY_2020_2_OR_NEWER
#nullable restore
#endif
