// <auto-generated/>

#if UNITY_2018_3_OR_NEWER
#define USE_SINGLE
#endif

#if UNITY_2020_2_OR_NEWER
#nullable enable
#endif

#if USE_SINGLE
using float_t = System.Single;
#else
using float_t = System.Double;
#endif

using System;
using System.Diagnostics.CodeAnalysis;

namespace AUTD3Sharp.Gain {
    public partial class Focus
    {
        
        public Focus WithIntensity(global::AUTD3Sharp.EmitIntensity value)
        {
           Intensity = value;
           return this;
        }

        [ExcludeFromCodeCoverage] public Focus WithIntensity(byte value)
        {
           Intensity = new EmitIntensity(value);
           return this;
        }
        public Focus WithPhaseOffset(global::AUTD3Sharp.Phase value)
        {
            PhaseOffset = value;
            return this;
        }
    }   
}