// <auto-generated/>

#if UNITY_2020_2_OR_NEWER
#nullable enable
#endif

using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace AUTD3Sharp {
    public partial struct ControlPoint
    {
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        [ExcludeFromCodeCoverage]
        public ControlPoint WithPhaseOffset(global::AUTD3Sharp.Phase value)
        {
           PhaseOffset = value;
           return this;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        [ExcludeFromCodeCoverage]
        public ControlPoint WithPhaseOffset(byte value)
        {
           PhaseOffset = new Phase(value);
           return this;
        }
    }   
}