name: 'build tools setup action'
inputs:
runs:
  using: "composite"
  steps:
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-make
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
