name: 'build tools setup action'
inputs:
  github-token:
    description: 'GITHUB_TOKEN'
    required: true
    default: ''
  os:
    description: 'os'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install packaging
      shell: bash
      run: |
        python3 -m pip install -U packaging requests

    - name: Setup .NET Core
      if: needs.check.outputs.status
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
