// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;
using AUTD3Sharp.Utils;
using AUTD3Sharp.Link;


namespace AUTD3Sharp.NativeMethods
{
    internal static unsafe partial class NativeMethodsAutd3LinkEthercrab
    {
        const string __DllName = "autd3_link_ethercrab";

        internal const nuint MAX_SUBDEVICES = 32;
        internal const nuint MAX_FRAMES = 16;



    }


    internal enum Status : byte
    {
        Error = 0,
        Lost = 1,
        StateChanged = 2,
        Resumed = 4,
    }


}
