// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;
using AUTD3Sharp.Utils;
using AUTD3Sharp.Link;


namespace AUTD3Sharp.NativeMethods
{
    internal static unsafe partial class NativeMethodsLinkRemote
    {
        const string __DllName = "autd3capi_link_remote";





        [DllImport(__DllName, EntryPoint = "AUTDLinkRemote", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ResultLink AUTDLinkRemote(byte* addr);


    }



}
