// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace AUTD3Sharp.NativeMethods
{
    public static unsafe partial class NativeMethodsModulationAudioFile
    {
        const string __DllName = "autd3capi_modulation_audio_file";



        [DllImport(__DllName, EntryPoint = "AUTDModulationWav", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ResultModulation AUTDModulationWav(byte* path, SamplingConfigurationRaw config);

        [DllImport(__DllName, EntryPoint = "AUTDModulationWavDefaultSamplingConfig", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern SamplingConfigurationRaw AUTDModulationWavDefaultSamplingConfig();

        [DllImport(__DllName, EntryPoint = "AUTDModulationRawPCM", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ResultModulation AUTDModulationRawPCM(byte* path, uint sample_rate, SamplingConfigurationRaw config);

        [DllImport(__DllName, EntryPoint = "AUTDModulationRawPCMDefaultSamplingConfig", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern SamplingConfigurationRaw AUTDModulationRawPCMDefaultSamplingConfig();


    }



}
    