// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;
using AUTD3Sharp.Utils;


namespace AUTD3Sharp.NativeMethods
{
    public static unsafe partial class NativeMethodsModulationAudioFile
    {
        const string __DllName = "autd3capi_modulation_audio_file";



        [DllImport(__DllName, EntryPoint = "AUTDModulationWav", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ResultModulation AUTDModulationWav(byte* path, LoopBehavior loop_behavior);

        [DllImport(__DllName, EntryPoint = "AUTDModulationWavIsDefault", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool AUTDModulationWavIsDefault(ModulationPtr wav);

        [DllImport(__DllName, EntryPoint = "AUTDModulationRawPCM", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ResultModulation AUTDModulationRawPCM(byte* path, uint sample_rate, LoopBehavior loop_behavior);

        [DllImport(__DllName, EntryPoint = "AUTDModulationCsv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ResultModulation AUTDModulationCsv(byte* path, uint sample_rate, byte deliminator, LoopBehavior loop_behavior);


    }



}
    