[package]
name = "wrapper-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.1"
anyhow = "1.0.75"
csbindgen = "1.9.0"
convert_case = "0.6.0"
regex = "1.10.2"
