name: build

on:
  push:
    branches:
      - 'develop'
  pull_request:
    types: [opened, reopened, review_requested]

env:
  CARGO_INCREMENTAL: 0

jobs:
  check:
    runs-on: ubuntu-latest
    name: check if files changed
    outputs:
      status: ${{ steps.changed-files.outputs.modified_files }}
    steps:
      - uses: actions/checkout@v3
      - uses: tj-actions/changed-files@v40
        id: changed-files
        with:
          files: |
            .github/actions/setup-build/action.yml
            .github/workflows/build-cs.yml
            src/AUTD3Sharp.csproj
            src/AUTD3Sharp.nuspec
            ./**/*.cs
            unity/Assets/package.json

  build:
    needs: check
    name: build-cs-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        if: needs.check.outputs.status
        uses: ./.github/actions/setup-build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          os: ${{ matrix.os }}

      - name: Setup .NET Core
        if: needs.check.outputs.status
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build cs library on ${{ matrix.os }}
        if: needs.check.outputs.status
        run: |
          python3 build.py cs build

      - name: Test library on ${{ matrix.os }}
        if: needs.check.outputs.status
        run: |
          python3 build.py cs test

      - name: Build fs library on ${{ matrix.os }}
        if: needs.check.outputs.status
        run: |
          python3 build.py fs build

  build-unity:
    needs: check
    name: build-unity-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        if: needs.check.outputs.status
        uses: ./.github/actions/setup-build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          os: ${{ matrix.os }}

      - name: Setup .NET Core
        if: needs.check.outputs.status
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build unity library on ${{ matrix.os }}
        if: needs.check.outputs.status
        run: |
          python3 build.py unity build
