name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  publish_unity:
    name: publish-unity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        run: |
          python3 build.py unity build --release
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish on npmjs
        continue-on-error: true
        run: |
          mv unity/Assets/Samples unity/Assets/Samples~
          rm -f unity/Assets/Samples.meta
          cd unity/Assets
          npm install
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


  publish_nuget:
    name: publish-nuget
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Get the version
      id: get_version
      run: echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3 | cut -d . -f 1,2,3)" >> $GITHUB_OUTPUT
    - name: Build with dotnet and publish to NuGet
      run: |
        python3 build.py cs build --release
        cd src/bin/Release
        dotnet nuget push autd3sharp.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate --no-symbols
